name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Public Repo
        run: |
          git remote add public https://noaht155:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/noaht155/noaht155.github.io.git
          git push public HEAD:refs/heads/main --force
